server:
  port: 8180

grpc:
  client:
    customer-service:
      address: static://localhost:9090
      negotiationType: plaintext
    wallet-service:
      address: static://localhost:9191
      negotiationType: plaintext